# Generated by Django 2.0.1 on 2020-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('book_banker1', 'book_banker'), ('home_decor1', 'home_decor'), ('agriculture', 'AGRICULTURE'), ('beauty_zone', 'beauty_zone'), ('travels', 'travels'), ('hospital', 'hospital'), ('travels', 'travels'), ('on_demand_service', 'on_demand_service'), ('bus_tickets', 'bus_tickets'), ('e_commerce', 'e_commerce'), ('functional_hall', 'functional_hall'), ('courier', 'courier'), ('automobile', 'automobile'), ('events', 'events'), ('dance_music_classes', 'dance_music_classes'), ('rechargers', 'rechargers'), ('books', 'books'), ('shoppings', 'shoppings'), ('flights', 'flights'), ('automobile', 'automobile'), ('insurance_zone', 'insurance_zone'), ('transport_services', 'transport_services'), ('automobile', 'automobile'), ('transport_services', 'transport_services'), ('sport_shops', 'sport_shops'), ('interior_design', 'interior_design'), ('sport_shops', 'sport_shops'), ('shopping', 'shopping'), ('sport_shops', 'sport_shops'), ('internet_shop', 'internet_shop'), ('workshops', 'workshops'), ('real_estate', 'real_estate'), ('play_shcool', 'play_shcool'), ('real_estate', 'real_estate'), ('domastic_help', 'domastic_help'), ('celebration_services', 'celebration_services'), ('apply_for_loans', 'apply_for_loans'), ('real_estate', 'real_estate'), ('doctors', 'doctors'), ('general_bazar', 'general_bazar'), ('petcare', 'petcare'), ('catering_services', 'catering_services'), ('jewellery', 'jewellery'), ('home_decor', 'home_decor'), ('book_banker', 'book_banker'), ('others', 'others')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proudct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agriculture', models.CharField(max_length=100)),
                ('beauty_zone', models.CharField(max_length=100)),
                ('travels', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('on_demand_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('cust_id', models.IntegerField()),
            ],
        ),
    ]
